### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by NicoCG** [scottbrady91/Passwordless-Authentication#1]
Hi @scottbrady91 ,

Love this idea login using an email address, how would you handle a user registering?

Would it be a good idea for the admin to invite the user to register?

Could you provide a unique register implementation?

**Comment by RyanOvO** [comment]
mark，that's awesome

**Comment by NicoCG** [comment]
@scottbrady91 I will be using https://github.com/PwdLess/Cierge until Registration implementation has been done.

**Comment by scottbrady91** [comment]
There's no difference to user registration using this approach than any other method. You simply don't ask them to set a password.

I recommend looking at the email confirmation APIs on the ASP.NET Core Identity UserManager.
